АДОЛЕ ФЕЙТ ЭНЕ
НПМБД 02 - 20




## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [3]:
import numpy as np

start = -1.3
end = 2.5
num_segments = 64

# Создаем равномерное разбиение интервала
intervals = np.linspace(start, end, num_segments+1)

# Печатаем массив
print(intervals)




[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [4]:
import numpy as np

def generate_cyclic_array(n):
    cyclic_pattern = np.array([1, 2, 3])
    length = 3 * n
    cyclic_array = np.tile(cyclic_pattern, n)[:length]
    return cyclic_array

n = 5 # Замените значение n на желаемое
result_array = generate_cyclic_array(n)
print(result_array)


[1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [5]:
# Создаем пустой массив
odd_numbers = []

# Используем цикл для генерации первых 10 нечетных чисел
for i in range(1, 20, 2):
    odd_numbers.append(i)

# Выводим результат
print(odd_numbers)


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [6]:
import numpy as np

# Создаем массив нулей размера 10x10
arr = np.zeros((10, 10))

# Добавляем "рамку" из единиц по краям
arr[0, :] = 1  # Первая строка
arr[-1, :] = 1  # Последняя строка
arr[:, 0] = 1  # Первый столбец
arr[:, -1] = 1  # Последний столбец

print(arr)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [7]:
# Создаем массив размером 8x8
chessboard = [[0 for _ in range(8)] for _ in range(8)]

# Заполняем шахматную доску
for i in range(8):
    for j in range(8):
        # Проверяем, должно ли поле содержать единицу
        if (i + j) % 2 == 1:
            chessboard[i][j] = 1

# Выводим шахматную доску
for row in chessboard:
    print(row)


[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [5]:
def create_matrix(n):
    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            row.append(i + j)
        matrix.append(row)
    return matrix

# Пример использования функции для создания матрицы 4x4
matrix = create_matrix(5)
print(matrix)


[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [7]:
import numpy as np

# Vector dot product
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
dot_product = np.dot(vector_a, vector_b)
print("Vector dot product:", dot_product)

# Matrix-vector multiplication
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector_c = np.array([2, 4, 6])
result_vector = np.dot(matrix_a, vector_c)
print("Matrix-vector multiplication:")
print(result_vector)

# Matrix-matrix multiplication
matrix_b = np.array([[1, 2], [3, 4], [5, 6]])
result_matrix = np.dot(matrix_a, matrix_b)
print("Matrix-matrix multiplication:")
print(result_matrix)



Vector dot product: 32
Matrix-vector multiplication:
[ 28  64 100]
Matrix-matrix multiplication:
[[ 22  28]
 [ 49  64]
 [ 76 100]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [9]:
import numpy as np

# Определение интервала [0, 1] с шагом 0.05
x = np.arange(0, 1.05, 0.05)

# Вычисление cos(x) и sin(x)
cos_values = np.cos(x)
sin_values = np.sin(x)

# Объединение результатов в один массив
combined_array = np.concatenate((cos_values, sin_values))

# Вывод результата
print(combined_array)



[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.54030231 0.         0.04997917 0.09983342
 0.14943813 0.19866933 0.24740396 0.29552021 0.34289781 0.38941834
 0.43496553 0.47942554 0.52268723 0.56464247 0.60518641 0.64421769
 0.68163876 0.71735609 0.75128041 0.78332691 0.8134155  0.84147098]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [11]:
import numpy as np

A = np.random.uniform(-1, 3, (3, 5))
print(A)


[[-0.22628025 -0.66623392  2.66456177 -0.34090908  2.84725545]
 [ 0.99206153  1.26651953 -0.02424737  0.30009494  0.82304539]
 [-0.80201975  0.95242323  0.93528729  0.7429465   0.77675653]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [12]:
import numpy as np

# Создание матрицы A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Сумма всех элементов
total_sum = np.sum(A)

# Сумма внутри строк
row_sums = np.sum(A, axis=1)

# Сумма внутри столбцов
column_sums = np.sum(A, axis=0)

# Среднее значение для каждой строки
row_means = np.mean(A, axis=1)

# Дисперсия для каждой строки
row_variances = np.var(A, axis=1)

# Стандартное отклонение для каждой строки
row_stddevs = np.std(A, axis=1)

print("Сумма всех элементов:", total_sum)
print("Сумма внутри строк:", row_sums)
print("Сумма внутри столбцов:", column_sums)
print("Среднее значение для каждой строки:", row_means)
print("Дисперсия для каждой строки:", row_variances)
print("Стандартное отклонение для каждой строки:", row_stddevs)


Сумма всех элементов: 45
Сумма внутри строк: [ 6 15 24]
Сумма внутри столбцов: [12 15 18]
Среднее значение для каждой строки: [2. 5. 8.]
Дисперсия для каждой строки: [0.66666667 0.66666667 0.66666667]
Стандартное отклонение для каждой строки: [0.81649658 0.81649658 0.81649658]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [16]:
import numpy as np

def normalize_matrix(A):
    # Вычисляем среднее значение каждой строки
    row_means = np.mean(A, axis=1)
    
    # Вычисляем стандартное отклонение каждой строки
    row_stdevs = np.std(A, axis=1)
    
    # Вычисляем количество строк и столбцов в матрице А
    m, n = A.shape
    
    # Создаем пустую матрицу B той же размерности, что и матрица А
    B = np.zeros((m, n))
    
    # Отнимаем от каждого элемента строки его среднее значение
    for i in range(m):
        B[i, :] = A[i, :] - row_means[i]
    
    # Разделяем каждый элемент строки на соответствующее стандартное отклонение
    for i in range(m):
        B[i, :] = B[i, :] / row_stdevs[i]
    
    return B

# Пример использования
A = np.array([[1, 5, 3],
              [4, 7, 6],
              [17, 4, 9]])

B = normalize_matrix(A)
print(B)


[[-1.06904497 -0.26726124  1.33630621]
 [-1.33630621  1.06904497  0.26726124]
 [ 1.30740289 -1.12063105 -0.18677184]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [17]:
import numpy as np

A = np.array([[4, 2, 5],
              [1, 6, 3],
              [7, 2, 9]])

sorted_indices = np.argsort(A[:, 2])
sorted_A = A[sorted_indices]

print(sorted_A)


[[1 6 3]
 [4 2 5]
 [7 2 9]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [18]:
import numpy as np

A = np.array([[2, 1],
              [3, 4],
              [1, 2]])

B = np.dot(A.T, A)
C = np.dot(A, A.T)

print("Матрица B:")
print(B)
print("Размер матрицы B:", B.shape)

print("\nМатрица C:")
print(C)
print("Размер матрицы C:", C.shape)


Матрица B:
[[14 16]
 [16 21]]
Размер матрицы B: (2, 2)

Матрица C:
[[ 5 10  4]
 [10 25 11]
 [ 4 11  5]]
Размер матрицы C: (3, 3)


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [19]:
import numpy as np

A = np.array([[2, 1],
              [3, 4],
              [1, 2]])

B = np.dot(A.T, A)
C = np.dot(A, A.T)

print("Матрица B:")
print(B)
print("Размер матрицы B:", B.shape)

print("\nМатрица C:")
print(C)
print("Размер матрицы C:", C.shape)

sum_B = np.trace(B)
sum_C = np.trace(C)

print("\nСумма диагональных элементов матрицы B:", sum_B)
print("Сумма диагональных элементов матрицы C:", sum_C)


Матрица B:
[[14 16]
 [16 21]]
Размер матрицы B: (2, 2)

Матрица C:
[[ 5 10  4]
 [10 25 11]
 [ 4 11  5]]
Размер матрицы C: (3, 3)

Сумма диагональных элементов матрицы B: 35
Сумма диагональных элементов матрицы C: 35


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [24]:
#print(np.linalg.det(matrix)) A не квадратная, ошибка.
print(np.linalg.det(B))
print(np.linalg.det(C))
print(np.linalg.matrix_rank(matrix))
print(np.linalg.matrix_rank(B))
print(np.linalg.matrix_rank(C))
w_b, v_b = np.linalg.eig(B)
w_c, v_b = np.linalg.eig(B)
print(w_b)
print(w_c)

37.99999999999999
0.0
2
2
2
[ 1.12166065 33.87833935]
[ 1.12166065 33.87833935]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [25]:
np.random.seed(1032205074)
np.random.randint(9)

1

In [26]:
print('Аналитическое решение интеграла 1: ', -2 * np.log(3) + 4 * np.log(2) - 1/2)
print('Аналитическое решение интеграла 2: ', np.pi/(2**(3/2)))

Аналитическое решение интеграла 1:  0.07536414490356158
Аналитическое решение интеграла 2:  1.1107207345395915


In [27]:
def func1(x):
    return (x+1)/(x**3-x**2)

def func2(x):
    return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)

def solution(func,a, b, dx, method):
    n = int((b-a) / dx)
    xx = np.linspace(a, b, n)
    if method == 'rectangular':
        return dx*np.sum(func(xx))
    elif method == 'trapezoid':
        return dx/2*(func(xx[0]) + 2*np.sum(func(xx[1:-1])) + func(xx[-1]))
    elif method == 'simpson':
        return dx/3*(func(xx[0]) + 2*np.sum(func(xx[2:-1:2])) + 4*np.sum(func(xx[1:-2:2])) + func(xx[-1]))
    else:
        return 'Неверный метод'
    
print('Для интеграла 1:', solution(func1, -2, -1, 0.0001, 'rectangular'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'rectangular') )
print('Для интеграла 1:', solution(func1, -2, -1, 0.0001, 'trapezoid'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'trapezoid') )
print('Для интеграла 1:', solution(func1, -2, -1, 0.0001, 'simpson'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'simpson') )

Для интеграла 1: 0.07536077471587936 Для интеграла 9: 1.1041419998928388
Для интеграла 1: 0.07535660804921268 Для интеграла 9: 1.1041172156215913
Для интеграла 1: 0.07535660765565484 Для интеграла 9: 1.1032101773676126
